### ISSUE TITLE
Not a bug - just a question

### ISSUE THREAD

**Issue by mbparker** [dstaley/ipod-read-sysinfo-extended-macos#1]
Hi @dstaley  - I came here by way of your blog post about iPods in 2023. 

Having used sharepod_lib myself for years (I was sad to see him sell it off - and subsequently disappear) I've been recently looking for a way to extract the embedded XML Property List from my pre-iOS iPods on my mac.

This is the ONLY solution I could find - and it worked great - Kudos!

I'm just curious why you chose Rust to code it. Do you think one could do the equivalent in .NET 7 via P/Invoke to libusb (ugh, C) - if that was the tech stack one had to work with? 

Thanks

**Comment by mbparker** [comment]
Hah - after looking at your code, and the rusb dependency (which is just a libusb wrapper) I think I've answered my own questions.

**Comment by dstaley** [comment]
Yup, anything that can call into libusb should work! I used Rust because I had hoped to be able to use this cross platform, but unfortunately what works on macOS doesn't work on Windows.
